### ISSUE TITLE
MSVC编译问题

### ISSUE THREAD

**Issue by laper32** [jks-liu/coroutine-thread-pool.h#1]
`std::atomic_flag m_must_return_nullptr = false;` 在 [thread-safe-queue.h, Line57](https://github.com/jks-liu/coroutine-thread-pool.h/blob/master/src/thread-safe-queue.h#L57) 有编译错误：
> “std::atomic_flag::atomic_flag(const std::atomic_flag &)”: 无法将参数 1 从“bool”转换为“const std::atomic_flag &”

如果将 `std::atomic_flag m_must_return_nullptr = false;` 修改为 `std::atomic_flag m_must_return_nullptr = ATOMIC_FLAG_INIT;`，这部分正常，但会出现另一个错误： future<T> 没有合适的构造函数可用 
> 我用T是因为test里面所有future<>都编译失败

编译器： MSVC 16.11, x86

**Comment by jks-liu** [comment]
不好意思，由于长假未能及时回复。

由于 C++20 保证 `std::atomic_flag` 被[默认初始化成清除的状态](https://en.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT)，所以可以简单地删除 `= false`，不需要显式初始化。

注：我已在 GCC 测试过，暂时没有 MSVC 环境，你可以试一下。

**Comment by laper32** [comment]
> 不好意思，由于长假未能及时回复。
> 
> 由于 C++20 保证 `std::atomic_flag` 被[默认初始化成清除的状态](https://en.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT)，所以可以简单地删除 `= false`，不需要显式初始化。
> 
> 注：我已在 GCC 测试过，暂时没有 MSVC 环境，你可以试一下。

hmmm...还是不行
报错信息依然是我刚开始提的 `no appropriate default constructor available`
我个人觉得可能方向不是这个

**Comment by jks-liu** [comment]
这应该是 MSVC 的一个已知 BUG[^1]，但由于修复这个 BUG 会影响 ABI 兼容性，所以还没有释出。下一个 vNext （ABI 不兼容版本）可能要等到 VS2022[^2]。你可以用[这个回答](https://stackoverflow.com/a/55695631/4144109)里的代码检测编译器有没有这个 BUG。

Workaround 方法：  
这个 BUG 要求 `jks::future` 是可默认构造的，所以给它加上一个就行（我已在 VS 2019 中试过）。由于实际逻辑中没有用到这个函数，所有对此函数的实现没有要求。

[^1]: https://developercommunity2.visualstudio.com/t/std::asyncs-std::future-doesnt-support/123622
[^2]: https://github.com/microsoft/STL/issues/169#issuecomment-864537586
