### ISSUE TITLE
How can we thread pool submit a_coroutine_return_string(int x) with input

### ISSUE THREAD

**Issue by chenscottus** [jks-liu/coroutine-thread-pool.h#2]
How can we thread pool submit a_coroutine_return_string(int x) with input?

Thanks,

**Comment by jks-liu** [comment]
You can try wrapping it into a lambda.

**Comment by chenscottus** [comment]
Sorry, I don't understand, I would like to submit a_coroutine_return_string(int x) with the input parameter, how can i do that? Thanks

**Comment by jks-liu** [comment]
Sorry for late reply, below is an example.

https://github.com/jks-liu/coroutine-thread-pool.h/blob/ce5d04c0d0874dae915adabaa7cf4ce0bf1d65f1/test/main.cpp#L83-L85

**Comment by jks-liu** [comment]
Feel free to reopen this issue if you have more questions.
